# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devx < Formula
  desc "DevX is a command-line tool designed to simplify the development workflow for containerized applications. It helps developers manage projects, build Docker images, and update deployments in Kubernetes environments."
  homepage "https://github.com/ZengineChris/devx"
  version "0.1.7"
  license "MIT"

  depends_on "colima" if OS.mac?

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ZengineChris/devx/releases/download/v0.1.7/devx_Darwin_x86_64.tar.gz"
      sha256 "4a498e3a5e1755bf3ff2b7f2cc081d12f5b5fd0852a49c283b1036b1e64cf56e"

      def install
        bin.install "devx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ZengineChris/devx/releases/download/v0.1.7/devx_Darwin_arm64.tar.gz"
      sha256 "db6c0bf9062be7203d3acc07e26d7819751f3dda9fa59e4a671c6e6bc7e12725"

      def install
        bin.install "devx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ZengineChris/devx/releases/download/v0.1.7/devx_Linux_x86_64.tar.gz"
        sha256 "d8c7e19fec8c76ca9b21200d4d8de29369b3f66973aeaba95ad267c09495f285"

        def install
          bin.install "devx"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ZengineChris/devx/releases/download/v0.1.7/devx_Linux_arm64.tar.gz"
        sha256 "1afa42d5f23cbda0d08aa5d5811aae1b585b9155e34050c0918ff628a64f4f56"

        def install
          bin.install "devx"
        end
      end
    end
  end
end
