# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devx < Formula
  desc "A short description of your app"
  homepage "https://github.com/ZengineChris/devx"
  version "0.1.4"
  license "MIT"

  depends_on "colima" if OS.mac?

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ZengineChris/devx/releases/download/v0.1.4/devx_Darwin_x86_64.tar.gz"
      sha256 "c5ec923e50c4f2c4629e72f307b63618b9df53ff7052c060f4d3d8ad964adcdf"

      def install
        bin.install "devx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ZengineChris/devx/releases/download/v0.1.4/devx_Darwin_arm64.tar.gz"
      sha256 "41508d0759c262dfe070d9c87b44fb0f26c82708680ecabfbefbf1b0eec1ef20"

      def install
        bin.install "devx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ZengineChris/devx/releases/download/v0.1.4/devx_Linux_x86_64.tar.gz"
        sha256 "8ca38f5d7ca6112481f1779ea92f763c1f04b014db0f17ae9e43deae742d7276"

        def install
          bin.install "devx"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ZengineChris/devx/releases/download/v0.1.4/devx_Linux_arm64.tar.gz"
        sha256 "fc1f792f381cbfad04c595be4f9b2b7acba1be5918f91ef245889076d52fd744"

        def install
          bin.install "devx"
        end
      end
    end
  end
end
